---
# golangci-lint configuration.

version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/proofhouse/proofhouse-go)
        - blank
        - dot
        - alias
        - localmodule
      custom-order: true
    gofumpt:
      module-path: github.com/proofhouse/proofhouse-go
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/proofhouse/proofhouse-go
    golines:
      max-len: 120
